backend/controllers/ClientController.php
<?php

namespace backend\controllers;

use backend\src\helpers\client\ClientExportHelper;
use backend\src\useCase\client\SoftDeleteService;
use backend\src\useCase\clientCreate\ChildrenForm;
use backend\src\useCase\clientCreate\ClientCreateForm;
use backend\src\useCase\clientCreate\ClientCreateService;
use backend\src\useCase\clientCreate\ClientEmailForm;
use backend\src\useCase\clientCreate\ClientEmploymentDataForm;
use backend\src\useCase\clientCreate\ClientPassportDataForm;
use backend\src\useCase\clientCreate\ClientPhoneForm;
use backend\src\useCase\clientUpdate\ClientUpdateForm;
use backend\src\useCase\clientUpdate\ClientUpdateService;
use frontend\src\forms\login\LoginPartnerForm;
use Yii;
use common\src\entities\client\entity\Client;
use common\src\entities\client\entity\ClientSearch;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii2mod\rbac\filters\AccessControl;

/**
 * ClientCrudController implements the CRUD actions for Client model.
 *
 * @property-read ClientCreateService $clientCreateService
 * @property-read ClientUpdateService $clientUpdateService
 * @property-read SoftDeleteService $softDeleteService
 * @property-read ClientExportHelper $clientExportHelper
 */
class ClientController extends AuthController
{
    private ClientCreateService $clientCreateService;
    private ClientUpdateService $clientUpdateService;
    private SoftDeleteService $softDeleteService;
    private ClientExportHelper $clientExportHelper;

    public function __construct(
        $id,
        $module,
        ClientCreateService $clientCreateService,
        ClientUpdateService $clientUpdateService,
        SoftDeleteService $softDeleteService,
        ClientExportHelper $clientExportHelper,
        $config = []
    ) {
        $this->clientCreateService = $clientCreateService;
        $this->clientUpdateService = $clientUpdateService;
        $this->softDeleteService = $softDeleteService;
        $this->clientExportHelper = $clientExportHelper;
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $behaviors = [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['list-ajax'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
        return ArrayHelper::merge(parent::behaviors(), $behaviors);
    }

    /**
     * Lists all Client models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'additionalExportColumns' => $this->clientExportHelper->getAdditionalExportColumns()
        ]);
    }

    /**
     * Displays a single Client model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Client model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $post = Yii::$app->request->post();

        $model = new ClientCreateForm(
            count($post[ChildrenForm::getFormName()] ?? []),
            count($post[ClientEmploymentDataForm::getFormName()] ?? []),
            count($post[ClientEmailForm::getFormName()] ?? []),
            count($post[ClientPhoneForm::getFormName()] ?? [])
        );

        if (isset($post[ChildrenForm::getFormName()])) {
            $post[ChildrenForm::getFormName()] = array_values($post[ChildrenForm::getFormName()]);
        }
        if (isset($post[ClientEmailForm::getFormName()])) {
            $post[ClientEmailForm::getFormName()] = array_values($post[ClientEmailForm::getFormName()]);
        }
        if (isset($post[ClientPhoneForm::getFormName()])) {
            $post[ClientPhoneForm::getFormName()] = array_values($post[ClientPhoneForm::getFormName()]);
        }
        if (isset($post[ClientEmploymentDataForm::getFormName()])) {
            $post[ClientEmploymentDataForm::getFormName()] = array_values($post[ClientEmploymentDataForm::getFormName()]);
        }

        if ($model->load($post) && $model->validate()) {
            try {
                $client = $this->clientCreateService->create($model);
                return $this->redirect(['view', 'id' => $client->c_id]);
            } catch (\Throwable $e) {
                $model->addError('general', $e->getMessage());
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Client model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        $clientUpdateForm = new ClientUpdateForm($model);

        if ($clientUpdateForm->load(Yii::$app->request->post()) && $clientUpdateForm->validate()) {
            $this->clientUpdateService->update($clientUpdateForm, Yii::$app->request->post());
            if (!$clientUpdateForm->hasErrors()) {
                return $this->redirect(['view', 'id' => $model->c_id]);
            }
        }

        return $this->render('update', [
            'model' => $clientUpdateForm,
        ]);
    }

    /**
     * Deletes an existing Client model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $client = $this->findModel($id);

        if ($client->loanApplications) {
            Yii::$app->session->setFlash('error', Yii::t('client', 'Unable to delete a customer due to existing loan applications from the customer'));
        } else {
            $client->delete();
        }

        return $this->redirect(['index']);
    }

    public function actionSoftDelete($id)
    {
        $client = $this->findModel($id);
        if (!empty($client->c_deleted_dt)) {
            Yii::$app->session->setFlash('warning', Yii::t('client', 'Client already deleted'));
            return $this->redirect(['index']);
        }
        if (!$this->softDeleteService->encryptData($client)) {
            Yii::$app->session->setFlash('error', $this->softDeleteService->getErrorMessage());
        } else {
            Yii::$app->session->setFlash('success', Yii::t('client', 'User is soft deleted. All his sensitive data is encrypted.'));
        }
        return $this->redirect(['index']);
    }

    public function actionRestoreData($id)
    {
        $client = $this->findModel($id);
        if (empty($client->c_deleted_dt)) {
            Yii::$app->session->setFlash('warning', Yii::t('client', 'Clients data already restored'));
            return $this->redirect(['index']);
        }
        if (!$this->softDeleteService->decryptData($client)) {
            Yii::$app->session->setFlash('error', $this->softDeleteService->getErrorMessage());
        } else {
            Yii::$app->session->setFlash('success', Yii::t('client', 'User is restored. All his sensitive data is decrypted.'));
        }
        return $this->redirect(['index']);
    }

    public function actionSwitch()
    {
        $clientId = Yii::$app->request->get('id');
        $client = Client::findOne($clientId);
        if ($client) {
            Yii::$app->session->setName('advanced-frontend');
            if (Yii::$app->frontendUser->login($client, 0)) {
                (new LoginPartnerForm())->sendWsIdentityCookie($client, 0);
            } else {
                Yii::$app->session->setFlash('error', Yii::t('frontend', 'Cannot login to the client profile.'));
                return $this->redirect(['/client/index']);
            }
        }
        return $this->redirect(Yii::$app->params['frontendHost'] . '/cabinet/loan-application-list');
    }

    /**
     * @param string|null $q
     * @param int|null $id
     * @return array
     */
    public function actionListAjax(?string $q = null, ?int $id = null): array
    {
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;

        $out = ['results' => ['id' => '', 'text' => '', 'selection' => '']];

        if ($q !== null) {
            $query = Client::find();
            $data = $query->select(['id' => 'c_id', 'text' => new Expression('CONCAT(c_name, " ", c_last_name)')])
                ->where(['like', new Expression('CONCAT(c_name, " ", c_last_name)'), $q])
                ->orWhere(['c_id' => (int) $q])
                ->limit(20)
                //->indexBy('id')
                ->asArray()
                ->all();

            if ($data) {
                foreach ($data as $n => $item) {
                    $text = $item['text'] . ' (' . $item['id'] . ')';
                    $data[$n]['text'] = $this->formatText($text, $q);
                    $data[$n]['selection'] = $item['text'];
                }
            }

            $out['results'] = $data; //array_values($data);
        } elseif ($id > 0) {
            $client = Client::findOne($id);

backend/controllers/ClientNotificationController.php
<?php

namespace backend\controllers;

use backend\src\auth\Auth;
use Yii;
use common\src\entities\clientNotification\entity\ClientNotification;
use common\src\entities\clientNotification\entity\ClientNotificationSearch;
use backend\controllers\AuthController;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ClientNotificationController implements the CRUD actions for ClientNotification model.
 */
class ClientNotificationController extends AuthController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all ClientNotification models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ClientNotificationSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single ClientNotification model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ClientNotification model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ClientNotification();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->cn_id]);
            }
        } else {
            $model->cn_created_by = Auth::id();
            $model->cn_new = true;
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing ClientNotification model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->cn_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ClientNotification model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ClientNotification model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ClientNotification the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ClientNotification::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('client_notification', 'The requested page does not exist.'));
    }
}

backend/views/client-notification/_form.php
<?php

use common\src\entities\clientNotification\entity\ClientNotification;
use common\src\entities\users\entity\UsersQuery;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\src\entities\clientNotification\entity\ClientNotification */
/* @var $form yii\widgets\ActiveForm */
?>

<?php $form = ActiveForm::begin(); ?>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <?= $form->field($model, 'cn_client_id')->widget(\backend\widgets\ClientSelect2Widget::class, [
                    'useAjax' => true
            ]) ?>

            <?= $form->field($model, 'cn_type_id')->dropDownList(ClientNotification::getTypeList(), ['prompt' => '---']) ?>

            <?= $form->field($model, 'cn_new')->checkbox() ?>

            <?= $form->field($model, 'cn_deleted')->checkbox() ?>

            <?= $form->field($model, 'cn_created_by')->widget(\backend\widgets\UserSelect2Widget::class,[
                'data' => UsersQuery::getList()
            ]) ?>
        </div>


        <div class="col-md-6">
            <?= $form->field($model, 'cn_title')->textInput(['maxlength' => true]) ?>

            <?= $form->field($model, 'cn_message')->textarea(['rows' => 6]) ?>
        </div>

        <div class="col-md-12">
            <?= Html::submitButton(Yii::t('client_notification', 'Save'), ['class' => 'btn btn-success']) ?>
        </div>
    </div>
</div>
<?php ActiveForm::end(); ?>

backend/views/client-notification/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\src\entities\clientNotification\entity\ClientNotificationSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="client-notification-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'cn_id') ?>

    <?= $form->field($model, 'cn_unique_id') ?>

    <?= $form->field($model, 'cn_client_id') ?>

    <?= $form->field($model, 'cn_type_id') ?>

    <?= $form->field($model, 'cn_title') ?>

    <?php // echo $form->field($model, 'cn_message') ?>

    <?php // echo $form->field($model, 'cn_new') ?>

    <?php // echo $form->field($model, 'cn_deleted') ?>

    <?php // echo $form->field($model, 'cn_popup') ?>

    <?php // echo $form->field($model, 'cn_popup_show') ?>

    <?php // echo $form->field($model, 'cn_read_dt') ?>

    <?php // echo $form->field($model, 'cn_created_dt') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('client_notification', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('client_notification', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/client-notification/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\src\entities\clientNotification\entity\ClientNotification */

$this->title = Yii::t('client_notification', 'Create Client Notification');
$this->params['breadcrumbs'][] = ['label' => Yii::t('client_notification', 'Client Notifications'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-notification-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/client-notification/index.php
<?php

use backend\components\grid\DateTimeColumn;
use backend\components\grid\UserSelect2Column;
use common\src\entities\clientNotification\entity\ClientNotification;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\src\entities\clientNotification\entity\ClientNotificationSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('client_notification', 'Client Notifications');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="client-notification-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('client_notification', 'Create Client Notification'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'cn_id',
                'options' => [
                    'width' => '100px'
                ]
            ],
            'cn_unique_id',
            [
                'attribute' => 'cn_client_id',
                'value' => static function (ClientNotification $model) {
                    return Html::a('('.$model->cn_client_id.') ' . $model->client->getFullName(), ['/client/view', 'id' => $model->cn_client_id], [
                        'target' => '_blank',
                        'data-pjax' => 0
                    ]);
                },
                'format' => 'raw',
            ],
            [
                'attribute' => 'cn_type_id',
                'value' => static function (ClientNotification $model) {
                    return '<span class="label label-default">' . ClientNotification::getType($model->cn_type_id) . '</span>';
                },
                'format' => 'raw',
                'filter' => ClientNotification::getTypeList()
            ],
            'cn_title',
            'cn_new:booleanByLabel',
            'cn_deleted:booleanByLabel',
            [
                'class' => DateTimeColumn::class,
                'attribute' => 'cn_read_dt'
            ],
            [
                'class' => DateTimeColumn::class,
                'attribute' => 'cn_created_dt'
            ],
            [
                'class' => UserSelect2Column::class,
                'attribute' => 'cn_created_by',
                'relation' => 'user',
                'placeholder' => '',
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view} {delete}'
            ],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

backend/views/client-notification/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\src\entities\clientNotification\entity\ClientNotification */

$this->title = Yii::t('client_notification', 'Update Client Notification: {name}', [
    'name' => $model->cn_id,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('client_notification', 'Client Notifications'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->cn_id, 'url' => ['view', 'id' => $model->cn_id]];
$this->params['breadcrumbs'][] = Yii::t('client_notification', 'Update');
?>
<div class="client-notification-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/client-notification/view.php
<?php

use common\src\entities\clientNotification\entity\ClientNotification;
use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\src\entities\clientNotification\entity\ClientNotification */

$this->title = $model->cn_title;
$this->params['breadcrumbs'][] = ['label' => Yii::t('client_notification', 'Client Notifications'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="client-notification-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('client_notification', 'Update'), ['update', 'id' => $model->cn_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('client_notification', 'Delete'), ['delete', 'id' => $model->cn_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('client_notification', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'cn_id',
            'cn_unique_id',
            [
                'attribute' => 'cn_client_id',
                'value' => static function (ClientNotification $model) {
                    return Html::a('('.$model->cn_client_id.') ' . $model->client->getFullName(), ['/client/view', 'id' => $model->cn_client_id], [
                        'target' => '_blank',
                        'data-pjax' => 0
                    ]);
                },
                'format' => 'raw',
            ],
            [
                'attribute' => 'cn_type_id',
                'value' => static function (ClientNotification $model) {
                    return '<span class="label label-default">' . ClientNotification::getType($model->cn_type_id) . '</span>';
                },
                'format' => 'raw',
            ],
            'cn_title',
            'cn_message:ntext',
            'cn_new:booleanByLabel',
            'cn_deleted:booleanByLabel',
            'cn_popup',
            'cn_popup_show',
            'cn_read_dt:byUserDateTime',
            'cn_created_dt:byUserDateTime',
            'cn_created_by:username'
        ],
    ]) ?>

</div>