backend/controllers/BlogCategoriesController.php
<?php

namespace backend\controllers;

use common\src\entities\language\LanguageQuery;
use common\src\helpers\app\AppHelper;
use Yii;
use common\src\entities\blog\categories\entity\BlogCategories;
use common\src\entities\blog\categories\entity\BlogCategoriesSearch;
use yii\db\Exception;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii2mod\rbac\filters\AccessControl;

/**
 * BlogCategoriesController implements the CRUD actions for BlogCategories model.
 */
class BlogCategoriesController extends AuthController
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $behaviors = [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    [
                        'actions' => ['generate-url'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
        return ArrayHelper::merge(parent::behaviors(), $behaviors);
    }

    /**
     * Lists all BlogCategories models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BlogCategoriesSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single BlogCategories model.
     * @param integer $bc_id
     * @param string $bc_lang_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($bc_id, $bc_lang_id)
    {
        return $this->render('view', [
            'model' => $this->findModel($bc_id, $bc_lang_id),
        ]);
    }

    /**
     * Creates a new BlogCategories model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new BlogCategories();

        if ($model->load(Yii::$app->request->post())) {
            try {
                $activeLanguages = LanguageQuery::getList();
                foreach ($activeLanguages as $langId => $langAbbrv) {
                    $model->bc_lang_id = $langId;
                    if ($model->save()) {
                        $model->setIsNewRecord(true);
                    } else {
                        throw new \RuntimeException($model->getErrorSummary(true));
                    }
                }
                Yii::$app->session->setFlash('success', Yii::t('backend', 'Category successfully created'));
                return $this->redirect(['view', 'bc_id' => $model->bc_id, 'bc_lang_id' => $model->bc_lang_id]);
            } catch (\RuntimeException | Exception $e) {
                $model->addError('general', $e->getMessage());
            }
        }
        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing BlogCategories model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $bc_id
     * @param string $bc_lang_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($bc_id, $bc_lang_id)
    {
        $model = $this->findModel($bc_id, $bc_lang_id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', Yii::t('backend', 'Category successfully updated'));
            return $this->redirect(['view', 'bc_id' => $model->bc_id, 'bc_lang_id' => $model->bc_lang_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing BlogCategories model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $bc_id
     * @param string $bc_lang_id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($bc_id, $bc_lang_id)
    {
        $this->findModel($bc_id, $bc_lang_id)->delete();
        Yii::$app->session->setFlash('success', Yii::t('backend', 'Category successfully deleted'));
        return $this->redirect(['index']);
    }

    /**
     * Finds the BlogCategories model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $bc_id
     * @param string $bc_lang_id
     * @return BlogCategories the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($bc_id, $bc_lang_id)
    {
        if (($model = BlogCategories::findOne(['bc_id' => $bc_id, 'bc_lang_id' => $bc_lang_id])) !== null) {
            return $model;
        }

        throw new NotFoundHttpException(Yii::t('backend', 'The requested page does not exist.'));
    }

    public function actionGenerateUrl()
    {
        $name = Yii::$app->request->get('name');
        return AppHelper::stringToUrl($name, 255);
    }
}

backend/views/blog-categories/_form.php
<?php

use common\src\entities\language\LanguageQuery;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\src\entities\blog\categories\entity\BlogCategories */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="blog-categories-form">
    <div class="row">
        <div class="col-md-4">
            <?php $form = ActiveForm::begin(); ?>

            <?= $form->errorSummary($model, ['class' => 'alert alert-danger', 'role' => 'alert']) ?>

            <?php if ($model->bc_id): ?>
                <?= $form->field($model, 'bc_lang_id')->dropDownList(LanguageQuery::getList(), ['prompt' => '---']) ?>
            <?php endif; ?>

            <?= $form->field($model, 'bc_name')->textInput(['maxlength' => true, 'id' => 'name']) ?>

            <?= $form->field($model, 'bc_url')->textInput(['maxlength' => true, 'id' => 'url-address']) ?>

            <div class="form-group">
                <?= Html::submitButton(Yii::t('backend', 'Save'), ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

<?php
$generateUrl = \yii\helpers\Url::to(['/blog-categories/generate-url']);
$js = <<<JS
$(document).on('change', '#name', function () {
    let name = $(this).val();
    $.get('$generateUrl' + '?name=' + name, function (url) {
        $('#url-address').val(url);
    });
});
JS;
$this->registerJs($js);

backend/views/blog-categories/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\src\entities\blog\categories\entity\BlogCategoriesSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="blog-categories-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'bc_id') ?>

    <?= $form->field($model, 'bc_lang_id') ?>

    <?= $form->field($model, 'bc_name') ?>

    <?= $form->field($model, 'bc_created_dt') ?>

    <?= $form->field($model, 'bc_updated_dt') ?>

    <?php // echo $form->field($model, 'bc_created_user_id') ?>

    <?php // echo $form->field($model, 'bc_updated_user_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('backend', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('backend', 'Reset'), ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/blog-categories/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\src\entities\blog\categories\entity\BlogCategories */

$this->title = Yii::t('backend', 'Create Blog Categories');
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Blog Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="blog-categories-create">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/blog-categories/index.php
<?php

use backend\components\grid\DateTimeColumn;
use backend\components\grid\UserSelect2Column;
use common\src\entities\language\LanguageQuery;
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
/* @var $this yii\web\View */
/* @var $searchModel common\src\entities\blog\categories\entity\BlogCategoriesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('backend', 'Blog Categories');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="blog-categories-index">

    <h3><?= Html::encode($this->title) ?></h3>

    <p>
        <?= Html::a(Yii::t('backend', 'Create Blog Categories'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'bc_id',
                'options' => [
                    'width' => '100px'
                ]
            ],
            [
                'attribute' => 'bc_lang_id',
                'options' => [
                    'width' => '100px'
                ],
                'filter' => LanguageQuery::getList()
            ],
            'bc_name',
            'bc_url:ntext',
            [
                'class' => DateTimeColumn::class,
                'attribute' => 'bc_created_dt',
                'format' => 'byUserDateTime'
            ],
            [
                'class' => DateTimeColumn::class,
                'attribute' => 'bc_updated_dt',
                'format' => 'byUserDateTime'
            ],
            [
                'class' => UserSelect2Column::class,
                'attribute' => 'bc_created_user_id',
                'relation' => 'createdUser',
                'placeholder' => '',
            ],
            [
                'class' => UserSelect2Column::class,
                'attribute' => 'bc_updated_user_id',
                'relation' => 'updatedUser',
                'placeholder' => '',
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>

    <?php Pjax::end(); ?>

</div>

backend/views/blog-categories/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\src\entities\blog\categories\entity\BlogCategories */

$this->title = Yii::t('backend', 'Update Blog Categories: {name}', [
    'name' => $model->bc_name,
]);
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Blog Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->bc_id, 'url' => ['view', 'bc_id' => $model->bc_id, 'bc_lang_id' => $model->bc_lang_id]];
$this->params['breadcrumbs'][] = Yii::t('backend', 'Update');
?>
<div class="blog-categories-update">

    <h3><?= Html::encode($this->title) ?></h3>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/blog-categories/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\src\entities\blog\categories\entity\BlogCategories */

$this->title = $model->bc_name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('backend', 'Blog Categories'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="blog-categories-view">

    <?= \yii\bootstrap\Alert::widget() ?>

    <h3><?= Html::encode($this->title) ?></h3>

    <p>
        <?= Html::a(Yii::t('backend', 'Update'), ['update', 'bc_id' => $model->bc_id, 'bc_lang_id' => $model->bc_lang_id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('backend', 'Delete'), ['delete', 'bc_id' => $model->bc_id, 'bc_lang_id' => $model->bc_lang_id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('backend', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <div class="row">
        <div class="col-md-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'bc_id',
                    'bc_lang_id',
                    'bc_name',
                    'bc_url:ntext',
                    'bc_created_dt',
                    'bc_updated_dt',
                    'bc_created_user_id',
                    'bc_updated_user_id',
                ],
            ]) ?>
        </div>
    </div>
</div>